package infoRed;

/**
 * Dialogo para mostrar el Acerca De
 * @version 2013
 * @serial 1.0
 * @author Juan Manuel / Abraham Lopez
 */
public class AcercaDe extends javax.swing.JDialog {
    
    /**
     * Creates new form AcercaDe
     */
    public AcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String descripcion ="                           Descripcion de la Aplicacion: ";
        descripcion +="\n";
        descripcion +="\n       Aplicacion creada para trabajar con una IP introducida.";
        descripcion +="\n       A partir de la IP tendremos diferentes opciones para";
        descripcion +="\n   trabajar con la red.";
        descripcion +="\n       Por ejemplo: obtencion de subredes, numero de hots, \n  cambio de bases, etc. .";
        String informacion ="\n                 Informacion Producto:";
        informacion +="\n";
        informacion +="\n       Nombre: infoRed";
        informacion +="\n       Versión: 1.0";
        informacion +="\n       Año: 2013";
        textDescripcion.setText(descripcion);
        textInformacion.setText(informacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        buttonCerrar = new javax.swing.JButton();
        labelImagen = new javax.swing.JLabel();
        textInformacion = new javax.swing.JTextArea();
        textDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca De InfoRed");

        panelContenedor.setBackground(new java.awt.Color(153, 204, 255));
        panelContenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoRed/fondo2.jpg"))); // NOI18N

        textInformacion.setEditable(false);
        textInformacion.setBackground(new java.awt.Color(153, 204, 255));
        textInformacion.setColumns(20);
        textInformacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textInformacion.setRows(5);
        textInformacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textInformacion.setOpaque(false);

        textDescripcion.setEditable(false);
        textDescripcion.setBackground(new java.awt.Color(153, 204, 255));
        textDescripcion.setColumns(20);
        textDescripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textDescripcion.setRows(5);
        textDescripcion.setToolTipText("Campo de texto con la descripcion del producto");
        textDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textDescripcion.setMaximumSize(new java.awt.Dimension(164, 94));
        textDescripcion.setMinimumSize(new java.awt.Dimension(164, 94));
        textDescripcion.setOpaque(false);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(labelImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(buttonCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textInformacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para cerrar el dialogo AcercaDe
     * @param evt 
     */
    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_buttonCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextArea textInformacion;
    // End of variables declaration//GEN-END:variables
}
