package infoRed;



/**
 * JPanel para establecer el fondo de la aplicacion
 * @version 2013
 * @serial 1.0
 * @author Juan Manuel / Abraham Lopez
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 450));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoRed/fondo.jpg"))); // NOI18N
        jLabel1.setToolTipText("contiene imagen de fondo");
        jLabel1.setFocusable(false);
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 450));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 450));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
