package infoRed;


import javax.swing.JOptionPane;


/**
 * Interfaz para pedir la direccion IP, numero bits robados
 * @version 2013
 * @serial 1.0
 * @author Juan Manuel / Abraham Lopez
 */
public class PedirDatosIpBitsRobados extends javax.swing.JDialog {
    //Atributos
    private InfoRed info;

    
    /**
     * Creates new form PedirIP
     * @param parent
     * @param modal
     */
    public PedirDatosIpBitsRobados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        info = (InfoRed) parent;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        buttonIngresarIP = new javax.swing.JButton();
        labelPedirIp1 = new javax.swing.JLabel();
        textBits = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Introducir IP");
        setMinimumSize(new java.awt.Dimension(300, 200));
        setResizable(false);

        panelContenedor.setToolTipText("Panel contenedor de pedir la IP");
        panelContenedor.setMaximumSize(new java.awt.Dimension(300, 200));
        panelContenedor.setMinimumSize(new java.awt.Dimension(300, 200));
        panelContenedor.setPreferredSize(new java.awt.Dimension(300, 200));

        buttonIngresarIP.setText("Ingresar Bits");
        buttonIngresarIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarIPActionPerformed(evt);
            }
        });

        labelPedirIp1.setText("Numero de bits a robar (mayor de 1):");
        labelPedirIp1.setToolTipText("label pidiendo la IP");

        textBits.setToolTipText("campo de texto para introducir el numero de bits robados");

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(labelPedirIp1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(textBits))
                .addContainerGap())
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(buttonIngresarIP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelPedirIp1)
                .addGap(18, 18, 18)
                .addComponent(textBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(buttonIngresarIP)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIngresarIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarIPActionPerformed
        // TODO add your handling code here:
        if(textBits.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Existen campos vacios, debe completarlos", "ERROR de lectura", 1);
        }else if(textBits.getText().equals("1")){
            JOptionPane.showMessageDialog(this, "No se puede robar solo 1 bit", "ERROR de lectura", 1);
        }else{   
        info.setBitsRobados(Integer.parseInt(textBits.getText().trim()));
        this.setVisible(false);
        }
    }//GEN-LAST:event_buttonIngresarIPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonIngresarIP;
    private javax.swing.JLabel labelPedirIp1;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JTextField textBits;
    // End of variables declaration//GEN-END:variables
}
